# Imagen base ligera y estable
FROM node:18-alpine

WORKDIR /usr/src/app

# Copiamos sólo package* primero para aprovechar cache
COPY package*.json ./
RUN npm ci --production

COPY . .

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "src/index.js"]
